export const central = [
    "Ang Thong",
    "Phra Nakhon Si Ayutthaya",
    "Bangkok",
    "Chai Nat",
    "Lop Buri",
    "Nakhon Pathom",
    "Nonthaburi",
    "Pathum Thani",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Saraburi",
    "Sing Buri",
    "Suphan Buri",
    "Nakhon Nayok",
    "Chachoengsao ",
    "Chanthaburi",
    "Chon Buri",
    "Prachin Buri",
    "Rayong",
    "Sa Kaeo",
    "Trat",
    "Kanchanaburi",
    "Ratchaburi",
    "Phetchaburi",
    "Prachuap Khiri Khan"
  ];
  
  export const north = [
    "Chiang Mai",
    "Chiang Rai",
    "Lampang",
    "Lamphun",
    "Mae Hong Son",
    "Nan",
    "Phayao",
    "Phrae",
    "Uttaradit",
    "Tak",
    "Sukhothai",
    "Phitsanulok",
    "Phichit",
    "Kamphaeng Phet",
    "Phetchabun",
    "Nakhon Sawan",
    "Uthai Thani"
  ];
  
  export const northeast = [
    "Amnat Charoen",
    "Bueng Kan",
    // "TH-38",
    "Buri Ram",
    "Chaiyaphum",
    "Kalasin",
    "Khon Kaen",
    "Loei",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nong Bua Lam phu",
    "Nong Khai",
    "Roi Et",
    "Sakon Nakhon",
    "Si Sa Ket",
    "Surin",
    "Ubon Ratchathani",
    "Udon Thani",
    "Yasothon"
  ];
  
  export const south = [
    "Chumphon",
    "Nakhon Si Thammarat",
    "Narathiwat",
    "Pattani",
    "Phatthalung",
    "Songkhla",
    "Surat Thani",
    "Yala",
    "Krabi",
    "Phang Nga",
    "Phuket",
    "Ranong",
    "Satun",
    "Trang"
  ];
  